# Generated by Django 4.1.7 on 2023-02-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.CharField(max_length=500)),
                ("created", models.DateField(auto_now=True)),
            ],
        ),
    ]
